'use client';
import { useMemo, useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import { Network, ContextPanel } from './stock-panels';
import { Activity, ArrowLeft, ArrowUpRight, ChevronRight, FileText, Layers, ShieldCheck, X, ChartNoAxesCombined } from 'lucide-react';
import { ResponsiveContainer, ComposedChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ReferenceArea, ReferenceLine, Legend } from 'recharts';
import { INVESTOR_TYPES, INSTITUTIONAL, COLORS, STOCKS, generateData, analyzeData } from './data';

const number = n => n.toLocaleString('ko-KR');
const signed = n => `${n > 0 ? '+' : ''}${number(n)}`;
const tone = grade => grade === '위험' ? 'danger' : grade === '주의' ? 'warning' : 'normal';
const tabs = ['핵심 분석', '수급 흐름', '공시·경보 이력'];
function Badge({ grade }) { return <span className={`badge ${tone(grade)}`}><i />{grade}</span>; }
function FlowTable({ current }) {
 const { result: r } = current;
 return <div className="table-scroll"><table><thead><tr><th>투자자 유형</th><th>당일 순매수</th><th>5일 누적</th><th>Z-score</th><th>상태</th></tr></thead><tbody>{INVESTOR_TYPES.map(inv => {
 const abnormal = r.abnormal.some(a => a.type === inv); const z = r.results[`${inv}_zscore`];
 return <tr key={inv}><td><span className="legend-dot" style={{ background: COLORS[inv] }} />{inv}</td><td className={r.latest[inv] > 0 ? 'positive' : 'negative'}>{signed(r.latest[inv])}</td><td>{signed(r.cum5[inv])}</td><td>{z === undefined ? '—' : z.toFixed(1) + 'σ'}</td><td><span className={abnormal ? 'text-danger' : 'muted'}>{abnormal ? '이상' : z === undefined ? '미평가' : '정상'}</span></td></tr>;
 })}<tr className="total"><td>기관 합계</td><td>{signed(r.instTotal)}</td><td>{signed(INSTITUTIONAL.reduce((s, inv) => s + r.cum5[inv], 0))}</td><td>—</td><td>—</td></tr></tbody></table></div>;
}
function Evidence({ current }) {
 const r = current.result;
 return <><div className="tags">{r.patternA && <span>복수 주체 동시 진입</span>}{r.patternB && <span>수급·가격 괴리</span>}</div><div className="evidence-grid">{r.abnormal.map(inv => <article className="evidence-card" key={inv.type}><div className="row"><span><span className="legend-dot" style={{background:COLORS[inv.type]}} />{inv.type}</span><details className="stat-help"><summary>통계 기준 ⓘ</summary><p>Z-score {inv.zscore}: 기준 평균보다 {inv.zscore} 표준편차 높음. 평균 대비 배수가 아닙니다.</p></details></div><h3>{signed(inv.amount)}<small> 억원</small></h3><p>평소 범위를 크게 웃도는 순매수입니다.</p><div className="card-foot">5일 누적 <strong>{signed(r.cum5[inv.type])}억원</strong></div></article>)}</div>{!r.abnormal.length && <div className="empty"><ShieldCheck size={36}/><h3>감지된 이상 패턴이 없습니다</h3><p>현재 예시 데이터는 설정된 탐지 기준 이내입니다.</p></div>}{r.patternB && <div className="divergence"><ChartNoAxesCombined size={24}/><div><strong>매수 흐름과 가격이 다른 방향으로 움직입니다</strong><p>기관 순매수 {signed(r.instTotal)}억원 · 전일 대비 종가 {r.returnPct}%. 이 지표만으로 움직임의 원인이나 향후 가격을 판단할 수 없습니다.</p></div></div>}</>;
}
function Charts({ current }) {
 const data = current.data;
 return <><div className="section-title"><div><h2>수급과 가격의 흐름</h2><p>20개 시점 예시 데이터 · 붉은 영역은 패턴 주입 구간</p></div><span className="unit">단위: 원 / 억원</span></div><div className="chart"><ResponsiveContainer width="100%" height={230}><ComposedChart data={data} margin={{left:8,right:16,top:12}}><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="date" tickLine={false} axisLine={false} minTickGap={35}/><YAxis domain={['auto','auto']} tickLine={false} axisLine={false} width={66}/><Tooltip formatter={v => [number(v)+'원','종가']}/>{data.at(-1).isAnomaly && <ReferenceArea x1="D-2" x2="D-0" fill="#ef6471" fillOpacity={0.09}/>}<Line dataKey="price" stroke="#203e66" strokeWidth={3} dot={false}/></ComposedChart></ResponsiveContainer></div><div className="chart"><ResponsiveContainer width="100%" height={260}><BarChart data={data} stackOffset="sign" margin={{left:8,right:16,top:12}}><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="date" tickLine={false} axisLine={false} minTickGap={35}/><YAxis tickLine={false} axisLine={false} width={66}/><Tooltip formatter={(v,n) => [signed(v)+'억원',n]}/><ReferenceLine y={0} stroke="#adb8c6"/>{data.at(-1).isAnomaly && <ReferenceArea x1="D-2" x2="D-0" fill="#ef6471" fillOpacity={0.09}/>}<Legend iconType="circle" iconSize={8}/>{INVESTOR_TYPES.map(inv=><Bar key={inv} dataKey={inv} stackId="flow" fill={COLORS[inv]} maxBarSize={24}/>)}</BarChart></ResponsiveContainer></div></>;
}
export default function App({ ticker = null }) {
 const all = useMemo(() => Object.entries(STOCKS).map(([name,info])=>{ const data=generateData(name);return {name,info,data,result:analyzeData(data)};}).sort((a,b)=>b.result.score-a.result.score),[]);
 const [filter,setFilter]=useState('전체');const [tab,setTab]=useState('핵심 분석');const [report,setReport]=useState(false);const dialog=useRef(null);
 const current=all.find(s=>s.info.ticker===ticker);const r=current?.result;
 useEffect(()=>{if(report){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[report]);

 return <><header className="topbar"><div className="top-inner"><Link className="brand" href="/" aria-label="수급경보 목록"><span className="brand-icon"><Activity size={22}/></span>수급경보<span className="brand-en">FLOW SIGNAL</span></Link><nav className="mode-nav"><Link href="/" aria-current="page">수급 모니터</Link><Link href="/history">시장경보 이력</Link></nav></div></header><main className="workspace"><div className="breadcrumb">워크스페이스 <ChevronRight size={14}/> 수급 모니터 {current && <><ChevronRight size={14}/>{current.name}</>}</div>
 {!current ? <><div className="page-heading"><div><span className="eyebrow">MARKET MONITOR</span><h1>관심종목 수급 현황<span className="heading-dot"/></h1><p>평소와 다른 수급의 움직임을 확인하세요.</p></div><span className="date-label">DEMO 데이터</span></div><div className="summary-grid">{['전체','위험','주의','정상'].map((grade,i)=><button key={grade} className={`summary-card ${filter===grade?'selected':''}`} onClick={()=>setFilter(grade)}><span>{i===0?'모니터링 종목':grade+' 단계'}<span className={`tiny-dot ${tone(grade)}`}/></span><strong>{grade==='전체'?all.length:all.filter(s=>s.result.grade===grade).length}<small>종목</small></strong></button>)}</div><section className="panel list-panel"><div className="section-title"><div><h2>종목별 경보</h2><p>경보 점수순 · 종목을 선택해 근거를 확인하세요.</p></div><span className="unit">{filter} · {all.filter(s=>filter==='전체'||s.result.grade===filter).length}종목</span></div><div className="list-labels"><span>종목</span><span>기준 종가</span><span>경보 점수</span><span>상태</span></div>{all.filter(s=>filter==='전체'||s.result.grade===filter).map((s,i)=><Link className="stock-row" key={s.name} href={`/stock/${s.info.ticker}`}><div className="stock-identity"><span className={`stock-avatar avatar-${i%3}`}>{s.name.slice(0,1)}</span><div><strong>{s.name}</strong><small>{s.info.ticker} · {s.info.market} · {s.info.sector}</small></div></div><div className="stock-price"><strong>{number(s.result.latest.price)}원</strong><small className={Number(s.result.returnPct)<0?'negative':'positive'}>{s.result.returnPct}%</small></div><div className="stock-score"><strong>{s.result.score}<small> / 100</small></strong><div className="score-track"><i className={tone(s.result.grade)} style={{width:s.result.score+'%'}}/></div></div><div className="stock-status"><Badge grade={s.result.grade}/><ChevronRight size={18}/></div><p className="row-reason">{s.result.headline}</p></Link>)}{!all.some(s=>filter==='전체'||s.result.grade===filter)&&<div className="empty">해당 등급의 종목이 없습니다.</div>}</section><div className="method-note"><Layers size={18}/><span>시연용 규칙 점수 · 투자자별 순매수 편차와 수급·가격 괴리를 함께 확인합니다.</span></div></>:
 <><Link className="back" href="/"><ArrowLeft size={16}/> 종목 목록</Link><div className="detail-heading"><div><div className="row title-row"><h1>{current.name}</h1><Badge grade={r.grade}/></div><p>{current.info.ticker} · {current.info.market} · {current.info.sector}</p></div><button className="primary" onClick={()=>setReport(true)}><FileText size={17}/>리포트 보기</button></div><div className="metrics">{[{label:'기준 종가',value:number(r.latest.price),unit:'원',sub:`전일 대비 ${r.returnPct}%`},{label:'경보 점수',value:r.score,unit:'/ 100',sub:'규칙 기반 시연 점수'},{label:'동시 진입 유형',value:r.abnormal.length,unit:'개',sub:'순매수 Z-score > 2'},{label:'기관 순매수',value:signed(r.instTotal),unit:'억원',sub:'당일 기관 합계'}].map(m=><div className="metric" key={m.label}><span>{m.label}</span><strong>{m.value}<small>{m.unit}</small></strong><p>{m.sub}</p></div>)}</div><div className={`alert-panel ${tone(r.grade)}`}><div><span className="eyebrow">FLOW SIGNAL / {r.grade==='정상'?'NORMAL':'DETECTED'}</span><h2>{r.headline}</h2><p>투자자별 수급 편차와 가격 방향을 함께 확인하세요.</p><button onClick={()=>setTab('핵심 분석')}>탐지 근거 확인 <ArrowUpRight size={16}/></button></div><div className="score-ring" style={{'--score':r.score+'%'}}><div><strong>{r.score}</strong><span>경보 점수</span></div></div></div><nav className="tabs" aria-label="종목 분석">{tabs.map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="tab-content" key={tab}>
{tab==='핵심 분석'&&<><section className="panel"><div className="section-title"><h2>왜 이상한가?</h2><span className="demo">DEMO</span></div><Evidence current={current}/></section><Network current={current}/></>}
{tab==='수급 흐름'&&<><section className="panel"><Charts current={current}/></section><section className="panel"><div className="section-title"><h2>투자자별 상세 데이터</h2><span className="unit">단위: 억원</span></div><FlowTable current={current}/></section></>}
{tab==='공시·경보 이력'&&<ContextPanel current={current}/>}</div></>}
 <footer><ShieldCheck size={16}/><p>시뮬레이션 데이터로 구성된 데모입니다. 실제 시세·AI 모델 결과가 아니며, 투자 조언을 제공하지 않습니다.</p><span>수급경보 © 2026</span></footer></main>
 <dialog ref={dialog} onCancel={()=>setReport(false)} onClick={e=>{if(e.target===dialog.current)setReport(false);}} aria-labelledby="report-title">{current&&<><header className="report-header"><div><span className="eyebrow">ANALYSIS REPORT · DEMO</span><h2 id="report-title">{current.name} 수급 분석</h2><p>{current.info.ticker} · {current.info.market} · 마지막 예시 시점 D-0</p></div><button className="icon-button" aria-label="리포트 닫기" onClick={()=>setReport(false)}><X/></button></header><div className="report-body"><div className="report-summary"><Badge grade={r.grade}/><strong>{r.score} / 100</strong><p>{r.headline}</p></div><h3>핵심 요약</h3><p>기준 종가 {number(r.latest.price)}원 · 기관 순매수 {signed(r.instTotal)}억원 · 이상 순매수 {r.abnormal.length}개 유형</p><h3>탐지 근거</h3><Evidence current={current}/><h3>공시 확인</h3><p>DART 연결 전으로 관련 공시를 확인하지 않았습니다.</p><h3>해석</h3><p>{r.grade==='정상'?'설정된 통계 기준 내의 움직임입니다.':'기준 구간과 다른 수급 움직임이 관측됐습니다. 원인 확인에는 실제 수급 데이터와 공시 검토가 필요합니다.'}</p><p className="report-disclaimer">이 리포트는 예시 데이터와 규칙 기반 계산으로 작성되었습니다. XGBoost·GNN·LLM은 아직 연결되지 않았습니다. 투자 판단을 대신하지 않습니다.</p></div></>}</dialog></>;
}


