'use client';
import {useState} from 'react';
import Link from 'next/link';
import notices from './alerts.json';
import {INVESTOR_TYPES} from './data';
const signed=n=>(n>0?'+':'')+n.toLocaleString('ko-KR');
export function Network({current}){
 const [index,setIndex]=useState(19); const row=current.data[index];
 const baseline=current.data.slice(0,17);
 const abnormal=inv=>{if(!['금융투자','보험','투신','사모','은행','연기금'].includes(inv))return false; const vals=baseline.map(d=>d[inv]);const mean=vals.reduce((a,b)=>a+b,0)/17;const std=Math.sqrt(vals.reduce((a,b)=>a+(b-mean)**2,0)/17)||1;return (row[inv]-mean)/std>2;};
 return <section className="panel"><div className="section-title"><div><h2>투자자별 수급 관계망</h2><p>선의 굵기는 순매수·순매도 규모, 강조 테두리는 통계 기준 초과를 나타냅니다.</p></div><span className="demo">DEMO</span></div><div className="network-key"><span className="positive">━ 순매수</span><span className="negative">━ 순매도</span><span>◎ 이상 순매수</span></div><div className="network-scroll"><svg className="flow-network" viewBox="0 0 760 420" role="img" aria-label={`${current.name} ${row.date} 투자자별 수급 관계망`}><title>{current.name} 투자자별 순매수 관계</title>{INVESTOR_TYPES.map((inv,i)=>{const angle=i*Math.PI/4-Math.PI/2;const x=380+Math.cos(angle)*275;const y=210+Math.sin(angle)*150;const val=row[inv];const flagged=abnormal(inv);return <g key={inv}><title>{inv}: {signed(val)}억원{flagged?' · 이상 순매수':''}</title><line x1="380" y1="210" x2={x} y2={y} stroke={val>=0?'#cf6573':'#6298c9'} strokeWidth={1+Math.min(8,Math.abs(val)/130)} opacity={flagged?.85:.35}/><rect x={x-65} y={y-27} width="130" height="54" rx="12" fill="white" stroke={flagged?'#cc6678':'#dce4ed'} strokeWidth={flagged?2.5:1}/><text x={x} y={y-3} textAnchor="middle" fontSize="14" fill="#233a50">{inv}</text><text x={x} y={y+17} textAnchor="middle" fontSize="13" fill={val>=0?'#ad4356':'#3272ad'}>{signed(val)}억원</text></g>;})}<circle cx="380" cy="210" r="62" fill="#183751"/><text x="380" y="205" textAnchor="middle" fill="white" fontSize="17" fontWeight="700">{current.name}</text><text x="380" y="228" textAnchor="middle" fill="#c5d7e3" fontSize="13">{current.info.ticker}</text></svg></div><label className="network-slider">관측 시점 <strong>{row.date}</strong><input aria-label="관계망 관측 시점" type="range" min="0" max="19" value={index} onChange={e=>setIndex(Number(e.target.value))}/></label><p className="network-note">예시 수급을 시각화한 관계망입니다. GNN 추론 결과가 아닙니다. 통계 기준은 최초 17개 시점이며, 기준 구간 안의 비교는 설명용입니다.</p></section>;
}
export function ContextPanel({current}){
 const records=notices.records.filter(r=>r.ticker===current.info.ticker);
 return <><section className="panel"><div className="section-title"><h2>공시로 설명되는 움직임인가?</h2><span className="demo">연결 전</span></div><h3>DART 공시 확인 대기</h3><p className="context-copy">아직 공시 데이터를 조회하지 않았습니다. 관련 공시 유무와 수급 변화의 연관성은 판단하지 않습니다.</p></section><section className="panel"><div className="section-title"><div><h2>{current.name} 시장경보 이력</h2><p>업로드 파일의 실제 기록 · {notices.start} ~ {notices.end}</p></div><span className="real-data">실데이터</span></div>{records.length?<div className="table-scroll history-detail"><table><thead><tr><th>지정 유형</th><th>공시일</th><th>지정일</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.type}</td><td>{r.published}</td><td>{r.designated}</td></tr>)}</tbody></table></div>:<div className="empty"><h3>파일에 수록된 지정 기록이 없습니다</h3><p>다운로드 한도 3,000건 내의 검색 결과이며, 전체 기간에 경보가 없었다는 뜻은 아닙니다.</p></div>}<p className="context-copy">출처: {notices.source}. 과거 지정 기록은 현재 지정 상태를 뜻하지 않습니다. 예시 수급과 실제 지정 기록은 서로 연결된 분석 결과가 아닙니다.</p><Link className="context-link" href="/history">전체 시장경보 이력 보기 →</Link></section></>;
}

